service: default
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: run.app
  secure: always

libraries:
- name: MySQLdb
  version: "latest"
- name: ssl
  version: latest
- name: PIL
  version: latest

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*\.ts$
  - ^(.*/)?.*\.js.map$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^node_modules$
  - ^venv$
  - ^log\.txt$
  - ^\.idea$
  - ^\.git$
  - ^\.vscode$
  - ^configs$
